### 合并操作

In [1]:
import numpy as np 
x = np.array([1,2,3])
y = np.array([3,2,1])
x
y

array([3, 2, 1])

In [2]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [3]:
z= np.array([666,666,666])
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [4]:
A = np.array([[1,2,3],
            [4,5,6]])

In [5]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.concatenate([A,A],axis=1)    #axis = 1,沿第二个维度，即列的方向拼接

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
np.concatenate([A,z.reshape(1,-1)])    #concatenate只能处理维度一样的

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [9]:
A2 = np.concatenate([A,z.reshape(1,-1)]) 

In [10]:
np.vstack([A,z])    #在垂直方向叠在一起，容错性更好

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [11]:
B = np.full((2,2),100)
np.hstack([A,B])    #水平方向叠加，但维度不同可能会报错

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x1,x2,x3 = np.split(x,[3,7])   #（分割对象，分割点）

In [16]:
x1

array([0, 1, 2])

In [17]:
x2

array([3, 4, 5, 6])

In [18]:
C = np.arange(16).reshape(4,4)

In [19]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
C1,C2 = np.split(C,[2])
C1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
C3,C4 = np.split(C,[2],axis = 1)    #维度变成列的方向
C3

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [22]:
np.vsplit(A,[2])   #垂直方向上以第二列为分割点

[array([[1, 2, 3],
        [4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [23]:
np.vsplit(C,[2])  

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [26]:
left,right = np.hsplit(C,[2])  

In [27]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])