In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [4]:
x.ndim

1

In [5]:
X.ndim

2

In [6]:
x.shape

(10,)

In [7]:
X.shape

(3, 5)

In [8]:
x.size

10

In [9]:
X.size

15

## numpy.array的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X[0][0]    #不建议那么写

0

In [16]:
X[(2,2)]

12

In [17]:
X[2,2]     #更建议用这种方式

12

In [18]:
x[0:5]       #0到5但是不包含5

array([0, 1, 2, 3, 4])

In [19]:
x[::2]       #切片语法，从头到尾步长为2

array([0, 2, 4, 6, 8])

In [20]:
x[::-1]    #倒序输出

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
X[:2,:3]   #访问前两行，前三列

array([[0, 1, 2],
       [5, 6, 7]])

但如果采用python中的两个[][]方式访问，就会出现问题

In [22]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
X[:2]                   #前两行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
X[:2][:3]   #取上述元素的前三个元素，但是上面发现里面只有两个元素

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
X[:2,::2]    #前两行从头到尾间隔为2  

array([[0, 2, 4],
       [5, 7, 9]])

In [26]:
X[::-1,::-1]   #矩阵反转  

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [27]:
X[0]

array([0, 1, 2, 3, 4])

In [28]:
X[0,:]

array([0, 1, 2, 3, 4])

In [29]:
X[0,:].ndim

1

In [30]:
X[:,0]    #只取第一列

array([ 0,  5, 10])

In [31]:
X[:,0].ndim

1

In [32]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [33]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

python中直接改变子矩阵元素值，原矩阵的对应元素值是不变的，但是numpy中不是这样

In [34]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

由于numpy注重效率，故采用的是引用的方式调用取子矩阵，此时修改子矩阵会改变原矩阵，同理原矩阵修改也会改变子矩阵

使子矩阵和原矩阵不相关

In [35]:
subX = X[:2,:3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

### Reshape

In [36]:
x.shape

(10,)

In [37]:
x.ndim

1

In [38]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
x
A=x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
x            #x的类型是不会变得

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
B = x.reshape(1,10)   #B变成了二维数组，一行，10列

In [42]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

上面是两个[]

In [43]:
B.shape

(1, 10)

In [44]:
B.ndim

2

In [45]:
x.reshape(10,-1)    #-1是指让计算机自动计算此位置应为何值

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [46]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])