In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y= iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split

In [6]:
shuffle_indexes = np.random.permutation(len(X))     #求索引的乱序排列

In [7]:
shuffle_indexes

array([ 55,  89,  54,  26,   6,  28, 103, 123, 137, 143, 102, 124,  41,
        22,   3, 122,  83,  43,  33, 141,  15,  47,  86,  45,   4,  24,
        49,  96,  95,  72,  30,  63, 132, 110, 117,  62, 118,  82, 121,
        74,  98, 107,  68,  80,  67,  42,  78,  97,  40, 105,  14, 115,
       127, 134,  99,  10,  73,   7,  94,  75, 116,  35, 104,   2, 100,
       108,  79,  27,  92, 101,  31,  84, 128, 119,  50,  81,  87, 138,
        51,  61,  19,  29, 129,  23,  39,   0, 120,  13, 148, 131,  53,
       133, 114, 144,  25,  64,   5, 142, 140,  57, 111,  37, 125,  59,
        76,  93, 130, 149,  52, 109,  44, 106, 112,  20,  48,   8,  38,
        60,  18,  88,  56,  77,  71,  11,  69,  85, 146,  58, 126, 147,
        66,  12, 113, 139,  32, 136,  21, 135,  65,  16,  91,   9,  17,
        46,  34,   1,  70,  90, 145,  36])

In [8]:
test_ratio = 0.2    #测试数据集比例
test_size = int(len(X)*test_ratio)   #测试数据集大小

In [9]:
test_size

30

In [10]:
test_indexes = shuffle_indexes[:test_size]   #对应索引值
train_indexes = shuffle_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [14]:
import sys
sys.path.append("..")
from mymoudle.model_selection import train_test_split

In [15]:
X_train1,X_test1,y_train1,y_test1 = train_test_split(X,y)

In [16]:
print(X_train1.shape)
print(y_train1.shape)

(120, 4)
(120,)


In [23]:
from mymoudle.FKNN import KNNClassifier

In [24]:
my_knn_clf = KNNClassifier(k=3)

In [25]:
my_knn_clf.fit(X_train,y_train)

In [26]:
y_predict = my_knn_clf.predict(X_test)

In [27]:
y_predict

array([1, 1, 1, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 2])

In [28]:
y_test

array([1, 1, 1, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1])

In [29]:
sum(y_predict == y_test)

28

In [30]:
sum(y_predict == y_test)/len(y_test)

0.9333333333333333

### sklearn中的train_test_split

In [34]:
from sklearn.model_selection import train_test_split
X_train2,X_test2,y_train2,y_test2 = train_test_split(X,y,test_size = 0.2,random_state=666)

In [33]:
print(X_train2.shape)
print(y_train2.shape)

(120, 4)
(120,)
